
postgresql : &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: stage_fright_<%= Rails.env %>
  min_messages: ERROR


default: &defaults
  timeout: 5000
  # adapter: postgresql
  encoding: unicode
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>
  pool: 5

development:
  <<: *defaults
  # database: stage_fright_development


test:
  <<: *defaults
  # database: stage_fright_test

production:
  <<: *defaults
  # database: stage_fright_production
  # username: stage_fright
  # password: <%= ENV['STAGE_FRIGHT_DATABASE_PASSWORD'] %>
